GET http://localhost:3000

###

GET http://localhost:3000/62f42859c7577741bc8868bc

###
POST http://localhost:3000
Content-Type: application/json

{
"title": "TESTANDO",
"description": "Criar projeto simples com TESTANDO"

}

###

PUT http://localhost:3000/62f434271db28ef7a76b72cb
Content-Type: application/json

{

"description": "Criar projeto simples com NestJS"
}


###
DELETE http://localhost:3000/62f435ffb3c54e25df8cadeb